name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    name: Verify
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        java-version: [11]
      fail-fast: false

    steps:
      - name: Checkout source
        uses: actions/checkout@v5

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: maven

      - name: Compile source, lint and run tests
        run: make test

      - name: Parse test results
        uses: mikepenz/action-junit-report@v5
        if: ${{ always() }}
        with:
          check_name: Unit tests report
          require_tests: true
          report_paths: "**/target/*-reports/*.xml"
          follow_symlink: true
          updateComment: false
          skip_annotations: true
